services:
  - type: web
    name: estudio-contable
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
